---

# Generate SSH key
- name: Switch to root SSH key path
  set_fact: ssh_key_file={{ ssh_key_root_file }}
  when: ssh_key_user == host_root_user
- name: Generate SSH key
  user: name={{ ssh_key_user }} generate_ssh_key=yes ssh_key_file={{ ssh_key_file }} ssh_key_bits={{ ssh_key_bits }} ssh_key_comment={{ ssh_key_comment }}

# Create root's symlink (if enabled)
- name: Ensure root .ssh directory
  file: path={{ ssh_key_root_dir }} owner={{ host_root_user }} group={{ host_root_group }} mode=0700 state=directory
  when: ssh_key_root_link and ssh_key_user != host_root_user
- name: Link private key for the root user
  file: src={{ ssh_key_file }} dest={{ ssh_key_root_file }} state=link
  when: ssh_key_root_link and ssh_key_user != host_root_user
- name: Link public key for the root user
  file: src={{ ssh_key_file }}.pub dest={{ ssh_key_root_file }}.pub state=link
  when: ssh_key_root_link and ssh_key_user != host_root_user
